### ISSUE TITLE
Error in `dplyr::bind_cols()

### ISSUE THREAD

**Issue by siyunw** [padilr1/ChIPbinner#3]
Thank you, @padilr1, for making this package. 

When running the genic_intergenic_scatterplot, I got this error: "Error in `dplyr::bind_cols()`:
! Can't recycle `x.norm` (size 74948664) to match `y.norm` (size 55279019).
Run `rlang::last_trace()` to see where the error occurred.

Do you have any suggestions on calculating the norm. bw with a scaling factor if there were no internal spikeIn control?

Thank you very much,

**Comment by padilr1** [comment]
Hi,

Can you try running the 'pre_clust()'? It compares two samples and ensures they have overlapping bins. Alternatively, you can use "IRanges::subsetByOverlaps()" and find overlapping bins for the two samples being compared prior to input into genic_intergenic_scatterplot. 

If no 'spikeIn control' is available, you can use the genome-wide percentage information from mass-spectrometry. If it's CUT&RUN, you can the IgG ratios. If it's ChIP-Seq, our lab also had fairly good success by simply using the input for each sample for normalization. 

Hope that helps.

**Comment by siyunw** [comment]
Thank you very much, @padilr1. Could you please provide an example using the "IRanges::subsetByOverlaps()" approach?

**Comment by siyunw** [comment]
Thank you. I ran the subset overlaps() and got this error, 
Error in names(d) <- c(treated_samp_label, wildtype_samp_label) : 
  'names' attribute [] must be the same length as the vector [2]
Any suggestions?

**Comment by siyunw** [comment]
@padilr1  Could you please elaborate on how "chip sample library size," "control library size," and "scaling factor" were calculated for a specific sample? 
Thank you,
