### ISSUE TITLE
change PCA sample labels

### ISSUE THREAD

**Issue by siyunw** [padilr1/ChIPbinner#5]
Hi @padilr1, in addition to changing the colors, how can the user change the shape (circles and triangles) for each sample in the PCA plot?

Thank you!

**Comment by padilr1** [comment]
Unfortunately, this is not possible, unless you hard-code the function within the package.

**Comment by siyunw** [comment]
Okay, I understand. Thank you! What about extracting cluster coordinates from the ABC clusters?

**Comment by padilr1** [comment]
After running the "annotate_clust" function, you should have generated an R object called "cons.RData". That object should contain the cluster annotated A, B, C, D etc. as well as the corresponding genomic coordinators per each bin contained within the individual clusters.

**Comment by siyunw** [comment]
Thank you very much! Now able to write the cons containing the cluster to file.
